### ISSUE TITLE
IKEv2 support?

### ISSUE THREAD

**Issue by blalor** [halo/macosvpn#24]
Very cool utility, although I wish scutil would just do its dang job. :-)

Would it be possible to add IKEv2 support to this project?

**Comment by halo** [comment]
Hi! Thank you :)

While I believe it's possible to support IKEv2, I'm not sure it's needed. Because `.mobileconfig` files work pretty well on Sierra. I don't have a reference at hand now, though. I remember downloading a set of mobileconfig files from some vendor that I just double clicked and all VPNs were right there. I wouldn't know how to generate those mobileconfigs though. Probably with the Apple Configuration Generator.

I reckon that's not simple enough? :)

**Comment by blalor** [comment]
Thanks; I wasn't aware of those config files (but I figured I'd dive into something like that eventually for iOS support).  I'll dig into them, but I'm also working with client TLS certificates that are only good for a day, so I'm looking for something that will allow me to update the VPN config easily.

**Comment by halo** [comment]
Closing this because I don't think it's feasible. See https://github.com/halo/macosvpn/issues/25#issuecomment-287729929 :)
