### ISSUE TITLE
Barred applications from using VPN ? Or bypass vpn usage , so that some of application we want can use it.

### ISSUE THREAD

**Issue by kshitijgodara** [halo/macosvpn#32]
Hello, 

Great work. Really helped a lot.
I able to successfully create vpn tunnel from your code and i able to connect to this service using 
scutill command.

Now what i need is , i want to re-route traffic. So i can barred some applications from using VPN through my app. 
I read about Network extension custom protocol , there we can do something like that.
But as we are not using it , so it will not help .

Is it possible ? If it is how can i do it ? Any suggestions.

**Comment by halo** [comment]
Hi! Thank you for your kind words.

> Now what i need is , i want to re-route traffic. So i can barred some applications from using VPN through my app.

I'm not sure I understand. Can you give me some examples of what you're trying to achieve?

Are you saying that you want to prohibit *other* applications from using your tunnel? Or do you want to prevent any traffic *except* through your tunnel?

Either way, maybe [the pf firewall](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man5/pf.conf.5.html) is able to help you out here.

I have an [experimental](https://github.com/halo/Brick) GUI for pf but it only works on Yosemite. Something changed on SIerra so it does not work any more.

For example, [these two rules](https://github.com/halo/Brick/blob/00cb0b39715f4e1c6eacff6bd332ec98c1550470/Brick/Defaults.plist#L68-L82) make it so that **only** VPN traffic will ever leave your computer. A quick google revealed other examples such as [this](https://gist.github.com/scy/8122924) which might be what you want.

PS: Why not use the Network extension custom protocol? I have never used it, but if you say it can do what you want, why not give it a try? :)

**Comment by kshitijgodara** [comment]
we want to prevent few applications from using my tunnel. I don't want to prevent any traffic except through my tunnel. I want few apps to use system's default tunnel  if I prevented them to route traffic through my tunnel.

**Comment by halo** [comment]
I don't know whether that's feasible or even possible, sorry.

I suppose it's possible with custom network extensions, or kernel extensions such as [little snitch](http://asciithoughts.com/posts/2014/02/15/using-little-snitch-to-prevent-internet-access-without-vpn/) but that's cumbersome.

Someone else asked your question [here on stack](https://superuser.com/a/858576) and has not received a positive answer in years. I will close this issue now because it is not really related to `macosvpn` but to macOS itself. I suggest you ask your question there so you can reach a wider audience.

Good luck!
