### ISSUE TITLE
Adding PPTP configuration

### ISSUE THREAD

**Issue by soheilbm** [halo/macosvpn#4]
By any chance is it possible to add support for PPTP configuration ?

**Comment by halo** [comment]
Well, I don't know your use case, but the PPTP protocol is [utterly insecure](https://en.wikipedia.org/wiki/Point-to-Point_Tunneling_Protocol#Security).

Just because I wouldn't want to give the impression that it's a good idea to use PPTP, I would be very hesitant supporting it. 

In short: no, unless there is a really really good reason :)

**Comment by soheilbm** [comment]
oh ok. Meanwhile, is there anyway to connect to created VPN programatically too ?

**Comment by halo** [comment]
Google [says](http://blog.coriolis.ch/2014/06/27/start-vpn-when-waking-up/) this:  `scutil --nc start NameOfYourVPNGoesHere`

Unfortunately it doesn't work for me but gives me a popup warning :/

> The IPSec Shared Secret is missing. Verify your settings and try reconnecting.
