### ISSUE TITLE
homebrew build failure for version 1.0.0 

### ISSUE THREAD

**Issue by tiiiecherle** [halo/macosvpn#42]
Hey,

first of all thanks for this nice project.

We would like to try the new version early next year and I updated the [homebrew formula](https://github.com/Homebrew/homebrew-core/pull/48181) but the build failed.

I'm sorry I can't help here but hopefully you can ;)

Thanks in advance and Merry Christmas ;)

**Comment by halo** [comment]
Merry Christmas!

First of all, thank you for submitting a new formula to homebrew. It makes me feel like we're a team 😄 

I was able to recreate the error locally using the following command, so that was good!

```bash
brew install --build-from-source ~/Desktop/macosvpn.rb --verbose
```

As I understand it, when you install something with homebrew, that's run inside a sandbox to improve security. That sandbox does not allow git clone from external sources – which is what Xcode 11 does to download swift package dependencies.

I just published version 1.0.1 which does not depend on any external code sources during compilation. That should make homebrew happy.

Would you mind trying this in your formula PR? It works on my machine™️ 

```ruby
  url "https://github.com/halo/macosvpn/archive/1.0.1.tar.gz"
  sha256 "85f5051512e7b403980e40eea96cc4dc21205379ea89a2dfd4e5aed19f5f25ca"
```

**Comment by tiiiecherle** [comment]
Thanks a lot, I just updated the pull request ;)

**Comment by tiiiecherle** [comment]
Sorry to get back to you for more teamwork ;) as the [build failed](https://github.com/Homebrew/homebrew-core/pull/48181#issuecomment-569078354) again with other errors...

Would be very nice if you could look into this when you find the time. 

Thanks in advance

**Comment by halo** [comment]
Alas, I suspected Xcode version [7.3 specified here](https://github.com/Homebrew/homebrew-core/pull/48181/files#diff-83f05834c4474d2278ffb4b02a465bceR15) is too low. I myself [used 11.1](https://github.com/halo/macosvpn/blob/790303dea224e659d41d3d34389f036a10aedc26/macosvpn.xcodeproj/project.pbxproj#L405), could you try that instead in the formula?

**Comment by tiiiecherle** [comment]
Thanks, just updated the pull request, let's see what happens ;)

**Comment by halo** [comment]
It failed, I didn't notice the error at first. Will look into it.

**Comment by halo** [comment]
Ok the tests passed now, awaiting merge by the homebrew team. 

I better quickly close this issue before more goes wrong 😅 

Thank you for your patience and your help.

**Comment by tiiiecherle** [comment]
@halo Thanks for this project and all your help ;)
