### ISSUE TITLE
GUI for Mac?

### ISSUE THREAD

**Issue by CollinsVakayil** [halo/macosvpn#50]
It would be great to have an user friendly GUI. Any plans on that in the near future?

**Comment by halo** [comment]
Interesting. But that's definitely not planned or something I aspire. Because the system calls `macosvpn` performs can only be run with superuser-privileges. Something that a GUI is restricted to not be able to do – at all. 

The GUI would have to call out to another background process that has been granted superuser privileges. And that's where the complexity comes in. Those would be installed somewhere on your hard drive, they would run in the background without you noticing it, and the code would become irresponsibly complex (the whole API for those external helper tools is deprecated right now without a replacement as we speak).

Then, mind you, the whole point of `macosvpn` is so that you don't have to use the GUI which already exists. That is, system preferences :)

I'll close this issue for now, and I believe there is no incentive to re-program a GUI that already exists in the operating system, that people are somewhat familiar with.

Feel free to reopen should I have missed something :) I reckon that you point towards "user friendly" as the main selling point. And I agree, it could be done. But I don't think it's worth it. I'd much rather work [on these issues](https://github.com/halo/LinkLiar/issues) in another open source program, which have been stagnant for years :(
